config/routes.rb
Rails.application.routes.draw do
  
  get 'drivers/index'

  get 'places/index'
get 'students/index'

  root 'home#index'

get 'about'=>'about#index'
get 'home'=>'home#index'
resources  :students
resources :cabs
resources :drivers
#resources :students
get 'students/new', to: 'students#new'
post 'students/new', to: 'students#new'

 get 'students/index', to: 'students#index' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cab.rb
class Cab < ApplicationRecord
has_many :places
end

app/models/driver.rb
class Driver < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
belongs_to :cab
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  @page_title='About us';
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cabs_controller.rb
class CabsController < PlacesController  
  
  def index
  @cabs = Cab.all
  @page_title="Cabs";
  super
  end

  def show
  @cab= Cab.find(params[:id])
  end

  def new
  end

  def delete
  end

  def update
  end

private
def cab_params
params.require(:cab).permit(:name, :reg_no, :seats, :aircond, :monthly_rental)
end

end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
  	@places=Place.all
  end


private
def place_params
params.require(:place).permit(:cabs_id , :source , :destination , :via)
end 


end

app/controllers/students_controller.rb
class StudentsController < PlacesController

def index 
@students= Student.all
@places=Place.all	
#super
#@students = Student.new(student_params)
#@students.save
end
def show

	@student=Student.find(params[:id])
end

def new 
@student=Student.new({:name=>'E.g. Rahul'})
end

def create  
@places=Place.all	
@student = Student.new(student_params)
@places.each do |place|

 	
if  @student.save 

if place.destination=@student.pick_uo_loc
	redirect_to(student_path(@student)) and return # I HAVE TO REDIRECT TO SHOW PAGE 
## I think I have to change this to redirect to a- page where all the matching cabs are available ##
else 
	render('new') and return
end



else
redirect_to(cabs_path) and return
	end

end
end


def update
end

def destroy 
end
 
private

def student_params
params.require(:student).permit(:name, :roll, :address, :phone, :pick_uo_loc)
end


end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cab_helper.rb
module CabHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/about/index.html.erb
<h1>

<%= @page_title %>

</h1>
<p>Hello Everybody. This is NorthCap University presenting you a platform where you can book your cabs monthly without directly dealing with the cab owners on a fair and a genuine price</p>

<address>
Contact for all your queries-
Latika Mam<br>
Senior - HOD<br>
CSE Department<br>
9871641478<br>
<br><br><br><br>

Prepared by <br>
Gaurav Gulati<br>
<br><br><br><br>




The NorthsCap University<br>
Sector-23A<br>
Gurgaon<br>
122001
</address>

app/views/cabs/delete.html.erb
<h1>Cab#delete</h1>
<p>Find me in app/views/cab/delete.html.erb</p>

app/views/cabs/index.html.erb
<h1>Cabs#index</h1>
<p>Here is a list of all cabs available with us . Kindly press on the downward link to display various details about the cabs that might help the students to kindly search the perfect kind of cab according to their particular requirements.</p>

<h2>ALL CABS WITH TOTAL SEATING CAPACITY</h2>


<% @cabs.each do |cab|  %>
<body>
<ul class="list-group">
  <li class="list-group-item"><%=cab.name%>  <span class="badge"><%=cab.seats%></span></li>
</ul>
</body>
<%=link_to("Show Details ", { :controller=>'cabs' , :action=>'show', :id=>cab.id } , :class=>'action show')%>
<%  end  %>
 

app/views/cabs/new.html.erb
<h1>Cab#new</h1>
<p>Find me in app/views/cab/new.html.erb</p>

app/views/cabs/show.html.erb
<%=link_to("Previous page", cabs_path, :class=>'back-link')%>
<h1>Cab Details</h1>
<p>Find me in app/views/cab/show.html.erb</p>

<div class="cabs show">
	<h2> SHOW  CAB  </h2>

<div class="list-group">
  <a href="#" class="list-group-item">CAR NAME                 :<%=@cab.name%></a>
  <a href="#" class="list-group-item">MONTHLY FARE             : <%=@cab.monthly_rental%></a>
  <a href="#" class="list-group-item">REGISTERATION NUMBER     : <%=@cab.reg_no%></a>
<a href="#" class="list-group-item">TOTAL SEATS               : <%=@cab.seats%></a>
<a href="#" class="list-group-item">AIR CONDITIONING PRESENT  :<%=@cab.aircond  ? 'True' : 'False' %></a>

<a href="#" class="list-group-item">SOURCE     : <%=@cab.places.find_by(:cab_id=>@cab).source%></a>

<a href="#" class="list-group-item">ROUTE FOLLOWED     : <%=@cab.places.find_by(:cab_id=>@cab).via%></a>

<a href="#" class="list-group-item">DESTINATION     : <%=@cab.places.find_by(:cab_id=>@cab).destination%></a>
 
</div>

app/views/cabs/update.html.erb
<h1>Cab#update</h1>
<p>Find me in app/views/cab/update.html.erb</p>

app/views/drivers/index.html.erb
<h1>Drivers#index</h1>
<p>Find me in app/views/drivers/index.html.erb</p>

app/views/home/index.html.erb
  <head>
    <style>
      #map {
        height: 400px;
        width: 100%;
       }
p{
        font-size: 20px;
}       


h3{
	padding-left: 235px;
	color: darkgreen;

	}




	.mySlides {display:none}
.w3-left, .w3-right, .w3-badge {cursor:pointer}
.w3-badge {height:11px;width:11px;padding:0}
    </style>
  </head>


<body>

 <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                
                    <div class="intro-message">
                
                        <h1>Home Page</h1>
                        <hr class="intro-divider">
                </div>
              
                    </div>
                  </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->





<div class="w3-content w3-display-container" style="max-width:400px">
          <%= image_tag("our fleet.jpeg" , class: "img-responsive") %>
 <%= image_tag("download.jpeg" , class: "img-responsive") %>
 <%= image_tag("download(1).jpeg" , class: "img-responsive") %>
  <div class="w3-center w3-container w3-section w3-large w3-text-white w3-display-bottommiddle" style="width:50%">
  <div class="w3-left w3-hover-text-khaki" onclick="plusDivs(-1)">&#10094;</div>
  <div class="w3-right w3-hover-text-khaki" onclick="plusDivs(1)">&#10095;</div>
  <span class="w3-badge demo w3-border w3-transparent w3-hover-white" onclick="currentDiv(1)"></span>
  <span class="w3-badge demo w3-border w3-transparent w3-hover-white" onclick="currentDiv(2)"></span>
  <span class="w3-badge demo w3-border w3-transparent w3-hover-white" onclick="currentDiv(3)"></span>
  </div>
</div>

<script>
var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
  showDivs(slideIndex += n);
}

function currentDiv(n) {
  showDivs(slideIndex = n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demo");
  if (n > x.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
     x[i].style.display = "none";  
  }
  for (i = 0; i < dots.length; i++) {
     dots[i].className = dots[i].className.replace(" w3-white", "");
  }
  x[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " w3-white";
}
</script>


<h3> BOOK YOUR MONTHLY CABS WITH EASE </h3>


<p>
Online Cab Booking System specializing in Hiring cabs to students. It is an online system through which students can view 
available cabs; register the cabs, view profile and book cabs for monthly basis. 
Cab booking service is a majortransport service provided by the 
various local transportation companies to students  within a wide spectrum of prices. 
Mostly students living in the nearby towns and cities use cab service for their daily transportations need. This cab booking will done via the The NorthCap University and fulfils all the requirements and security standards set by the transport department and will provided at  nominal and genuine fares.
</p>
<br><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

    <h3>The NorthCap University Gurgaon , Sector - 23 A</h3>
    <div id="map"></div>
    <script>
      function initMap() {
        var uluru = {lat: 28.50417, lng: 77.049091};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 18,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBbYD5Ii7Ey42m11CtDI7TrLSm6VQ91qpY&callback=initMap">
    </script>


</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">


    <title><%= @page_title ? @page_title :'Welcome ' %> | CabMgmt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CAB BOOKING</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class=" <%=  params[:controller] == 'home' ? 'active' : ' '  %>" ><%= link_to'Home', home_path %></li>
            <li class=" <%=  params[:controller] == 'about' ? 'active' : ' '  %>"><%= link_to'About', about_path %></a></li>
            <li class=" <%=  params[:controller] == 'cab' ? 'active' : ' '  %>"><%= link_to'View Cabs', cabs_path %></a></li>
            <li class=" <%=  params[:controller] == 'student' ? 'active' : ' '  %>"><%= link_to'Book_Cabs',{:action=>'new', :controller=>"students" } %></a></li>
            </ul>
          <ul class="nav navbar-nav navbar-right">
          <li class="Dropdown">
<ul class= "dropdown-menu navbar-right" role="menu">     
</ul> 
          </ul>
        </div><!--/.nav-collapse --> 
      </div>
    </nav>

<header>
<div class="container">
  <h1> THE CAB BOOKING SYSTEM  <small><%= @page_title ? @page_title :'Welcome ' %></small></h1>
</div>
</header>

<section>
<div class="container">
    <%= yield %>
</div>   
</section>


  </body>
</html>

app/views/places/index.html.erb
<h1>Places#index</h1>
<p>Find me in app/views/places/index.html.erb</p>

app/views/students/index.html.erb
<h2> LIST OF STUDENTS WHO BOOKED CAB.... </h2>
<h4>FIND YOUR NAME IN THE LIST , IF NOT 
<br>
WE ARE SORRY THE CAB IS CURRENTLY NOT AVAILABLE IN YOUR AREA
</h4>

<%  @places.each do |place| %>  

<% @students.each do |stu|  %>
<body>

<% if place.destination=stu.pick_uo_loc %>


<ul class="list-group">
  <li class="list-group-item">STUDENT NAME : <%=stu.name%>, ADDRESS : <%=stu.address%>, <br> PICK UP LOCATION :  <%=stu.pick_uo_loc%>, <br> , CONTACT NO. : <%=stu.phone%></li>

</ul>
<% else %>
<% end  %>
</body>

<%  end  %>
<% end %>

app/views/students/new.html.erb
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Example of Bootstrap 3 Horizontal Form Layout</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> 
<style type="text/css">
    .bs-example{
      margin: 20px;
    }
  /* Fix alignment issue of label on extra small devices in Bootstrap 3.2 */
    .form-horizontal .control-label{
        padding-top: 7px;
    }
</style>
</head>


<body>
<div class="form-group">
<h4> CURRENTLY OUR CAB IS AVAILABLE IN ROHINI , FARIDABAD , NARAINA , PUNJABI BAGH , MOTIBAGH ONLY </h4>
<%= form_for(@student) do |f| %>
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name%>
  </p>
 
  <p>
    <%= f.label :Roll_Number %><br>
    <%= f.text_field :roll %>
  </p>
  <p>
    <%= f.label :Phone_Number %><br>
    <%= f.text_field :phone %>
  </p>
  <p>
    <%= f.label :Address %><br>
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :Your_Desired_Pick_Up_Location%><br>
    <%= f.text_field :pick_uo_loc %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>


<% end %>
</div>

</body>

app/views/students/show.html.erb
<h1>WELCOME <%= @student.name %></h1>
<h3>Congratulations!!!</h3>
<p>We have a cab that is available in your area and we have confirmed your booking.
<br>
You will shortly notified about payment option </p>


<h4>DETAILS: <br><br> LOCATION =  <%=@student.pick_uo_loc%> <br><br>
	CONTACT NO. : <%=@student.phone%> <br><br>
   CAB ARRIVAL TIMINGS FOR YOUR AREA: 7.00 a.m
</h4>